apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: explainer
  labels:
    name: explainer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: explainer
    spec:
      containers:
      - name: tdw-explainer
        image: gcr.io/scalable-ml/nlp_explainer:latest